### ISSUE TITLE
Update to ruby-standalone 1.8.0 and move pact details from the POST /pact call to the command line

### ISSUE THREAD

**Issue by bethesque** [pact-foundation/pact-js#105]
Instead of posting the consumer name, provider name, and pact file write mode in the POST /pact call here https://github.com/pact-foundation/pact-js/blob/master/src/dsl/mockService.js#L75, they should now be passed in to the command line `service` call using `--consumer`, `--provider` and `--pact-file-write-mode`

**TODO**:

- [x] Ensure `pact-node` is capable of accepting these fields (update: it needs `pact-file-write-mode`)
- [x] Add any missing parameters to `pact` to pass through to `pact-node`
- [x] Make fields as 'deprecated' in current API
- [ ] Update Documentation / Release Notes
- [ ] Decommission fields in current API and publish new major version

**Comment by mefellows** [comment]
Will need to raise this in the upstream `pact-node` repo as this is where the interaction with the CLI happens.

That being said, I believe we already do that - these fields are (or should/will be) optional - and perhaps we can deprecate them in the next major release.

**Comment by mefellows** [comment]
Just checked pact-node, it's just missing the `pact-file-write-mode`

**Comment by bethesque** [comment]
The consumer name/provider name are still mandatory. It's just that they should be provided in the start up command rather than in the POST /pact.

**Comment by mefellows** [comment]
cc: @mboudreau I assume this needs to go in pact-node?
