### ISSUE TITLE
Documentation: "Using Pact with Docker"

### ISSUE THREAD

**Issue by mefellows** [pact-foundation/pact-js#118]
Given the prevalence of Docker, in particular dev/test, we should have a first class example for people to use.

**TODO**:

- [ ] Use of Docker compose to demonstrate both consumer tests and provider verification
- [ ] How to separate the test container from the mock server container (could be running `pact-node`, [`pact-mock-service-docker`](https://github.com/pact-foundation/pact-mock-service-docker) or another variant)
- [ ] E2E example integrated into CI

See https://github.com/pact-foundation/pact-js/pull/115 for inspiration to create this article.

**Comment by mattcanty** [comment]
I'm putting together a piece on this. Although I'm approaching from the viewpoint of multiple teams, therefore I'll probably have separate consumer/producer directories with Dockerfiles within.

I'll watch this conversation and be sure to update with any progress I make.

I'm also going to see if I can show example of validating Swagger templates, appreciate this may be out of scope for this.

**Comment by mefellows** [comment]
See https://github.com/pact-foundation/pact-js/tree/feat/docker-example for a first cut at this.

**Comment by mefellows** [comment]
Closing this due to inactivity.
