### ISSUE TITLE
Expose FFI provider API in pact-core

### ISSUE THREAD

**Issue by mefellows** [pact-foundation/pact-js#674]
Make pact-core expose the FFI provider libs in (close to) the existing interface

**Provider**:
This is close to possible on the provider side, as the provider interface accepts a newline delimited set of arguments much like the current Ruby CLI (see https://github.com/pact-foundation/pact-js/blob/spike/ffi-provider/src/native/verifierService.ts)

Care will need to be taken here to have some nice error handling at the boundary, to catch segfaults and other nasties.

**TODO**:
- [x] fix bug with `--file` argument
- [x] fix error logging so it comes out sensibly
- [x] ability to set the log level (not just log env var)
- [x] consumer version selectors
- [x] set a different exit code for CLI invocation errors (to enable better console reporting)
- [x] configurable Rust HTTP client timeouts (e.g. state handlers, verification requests)
- [x] Disable SSL verification
- [x] Env vars for filtering verifications

**Comment by TimothyJones** [comment]
This is awesome! Thanks!

**Comment by mefellows** [comment]
PR for env vars + selectors: https://github.com/pact-foundation/pact-reference/pull/104

**Comment by mefellows** [comment]
RE:  fix error logging so it comes out sensibly

I think I could disable logging entirely from the FFI, but provide a handle to get the errors back, so the caller could sensibly interpret. Still thinking through exactly what I can provide, but that might help.

**Comment by TimothyJones** [comment]
Fixed by pact-core 13.x 🎉

**Comment by mefellows** [comment]
👏   amazing Tim!
