### ISSUE TITLE
Failing to test message meta data with matcher

### ISSUE THREAD

**Issue by NiklasEi** [pact-foundation/pact-js#763]
### Software versions

- **OS**: Linux (Ubuntu 18.04.5 LTS)
- **Consumer Pact library**: Pact JS v9.16.5
- **Provider Pact library**: Pact JVM v4.2.14
- **Node Version**: v14.5.0

### Issue Checklist

Please confirm the following:

- [x] I have upgraded to the latest
- [x] I have the read the FAQs in the Readme (some things suggested there don't work in my case e.g. #414)
- [x] I have triple checked, that there are **no unhandled promises** in my code and have [read](https://github.com/pact-foundation/pact-js/#test-fails-when-it-should-pass) the section on intermittent test failures
- [x] I have set my log level to debug and attached a log file showing the complete request/response cycle
- [x] For bonus points and virtual high fives, I have created a reproduceable git repository ([see below](https://github.com/pact-foundation/pact-js/issues/763#issuecomment-968736314)) to illustrate the problem

### Expected behaviour

When creating a `MessageConsumerPact` meta data can be checked with matchers (e.g. against a regex).

```ts
      .withMetadata({
        'content-type': 'application/json',
        kafka_topic: Matchers.term({
          generate: 'project-production-stage-topic',
          matcher: new RegExp('project-(production|validation)-stage-topic').source
        })
      })
```

should match with `project-production-stage-topic` and `project-validation-stage-topic` on the provider side.

The created meta data part of the pact file:
```
      "metaData": {
        "content-type": "application/json",
        "kafka_topic": {
          "json_class": "Pact::Term",
          "data": {
            "generate": "project-production-stage-topic",
            "matcher": {
              "json_class": "Regexp",
              "o": 0,
              "s": "project-(production|validation)-stage-topic"
            }
          }
        }
      }
```

### Actual behaviour

On the provider side this fails with
```
  State
    generates a message which
      has a matching body (OK)
      includes message metadata
        "kafka_topic" with value "project-production-stage-topic" (FAILED)

Failures:

1) State: generates a message which

    1.1) metadata: Expected metadata key 'kafka_topic' to have value '{json_class=Pact::Term, data={generate=project-production-stage-topic, matcher={json_class=Regexp, o=0, s=project-(production|validation)-stage-topic}}}' (LinkedHashMap) but was 'project-production-stage-topic' (String)
```

### Relevant log files

```
[2021-10-27 07:36:49.434 +0000] INFO (19895 on my-pc): pact-node@10.13.10:
[2021-10-27 07:36:49.735 +0000] INFO (19895 on my-pc): pact-node@10.13.10: Creating Pact Server with options:
{"consumer":"Service","cors":false,"dir":"/home/project/path/tests/contract/pacts","host":"127.0.0.1","log":"/home/project/path/tests/contract/pacts/ProviderService.log","pactFileWriteMode":"merge","provider":"ProviderService","spec":2,"ssl":false,"timeout":30000}
[2021-10-27 07:36:49.738 +0000] DEBUG (19895 on my-pc): pact-node@10.13.10: Starting pact binary '/home/project/path/node_modules/@pact-foundation/pact-node/standalone/linux-x64-1.88.77/pact/bin/pact-mock-service', with arguments [service --consumer Service --pact_dir /home/project/path/tests/contract/pacts --host 127.0.0.1 --log /home/project/path/tests/contract/pacts/ProviderService.log --pact-file-write-mode merge --provider ProviderService --pact_specification_version 2]
[2021-10-27 07:36:49.756 +0000] DEBUG (19895 on my-pc): pact-node@10.13.10: Created '/home/project/path/node_modules/@pact-foundation/pact-node/standalone/linux-x64-1.88.77/pact/bin/pact-mock-service' process with PID: 19937
[2021-10-27 07:36:50.292 +0000] DEBUG (19895 on my-pc): pact-node@10.13.10: INFO  WEBrick 1.3.1
INFO  ruby 2.2.2 (2015-04-13) [x86_64-linux]

[2021-10-27 07:36:50.293 +0000] DEBUG (19895 on my-pc): pact-node@10.13.10: INFO  WEBrick::HTTPServer#start: pid=19937 port=43853

[2021-10-27 07:36:50.293 +0000] INFO (19895 on my-pc): pact-node@10.13.10: Pact running on port 43853
[2021-10-27 07:36:50.775 +0000] INFO (19895 on my-pc): pact@9.16.5: Setting up Pact with Consumer "Service" and Provider "ProviderService"
    using mock service on Port: "43853"
... Service logs
[2021-10-27 07:36:50.975 +0000] DEBUG (19895 on my-pc): pact-node@10.13.10: WARN: Only the first item will be used to match the items in the array at $['body']

[2021-10-27 07:36:50.976 +0000] ERROR (19895 on my-pc): pact-node@10.13.10: Pact Binary Error: WARN: Only the first item will be used to match the items in the array at $['body'] <-- I don't understand this log, but since `body` is independent from the meta data matcher my assumption is that it has nothing to do with the here described issue

[2021-10-27 07:36:50.979 +0000] INFO (19895 on my-pc): pact@9.16.5: Pact File Written
[2021-10-27 07:36:50.979 +0000] INFO (19895 on my-pc): pact-node@10.13.10: Removing Pact process with PID: 19937
```

**Comment by bethesque** [comment]
Something is not right with the serialisation. Can you please create me a repo or a gist so I can investigate this?

**Comment by janeisenmenger** [comment]
Hello @bethesque.
I created a (actually two) repos in order to further investigate this issue. For context, the case here is that a typescript application is consuming messages that are created by a Java application, so we are using pact-js on one side and pact-jvm on the other. 

So here's what I did and found out.
On the JS side, we write the consumer test just as @NiklasEi  mentioned above and create a pact file. The repo can be found [here](https://github.com/janeisenmenger/pact-js-serialization-issue). There you'll find the consumer test as well as the pact file created by it.

On the JVM side, we write the provider test which gets the pact file we just created. Running this caused the error message that @NiklasEi added up top.

I recreated the consumer test on the JVM side in order to see whether there was any difference in the pact files, and there was:

Here's the relevant part from the JS created pact file
```
"matchingRules": {},
"metaData": {
	"content-type": "application/json",
	"kafka_topic": {
		"json_class": "Pact::Term",
		"data": {
			"generate": "project-production-stage-topic",
			"matcher": {
				"json_class": "Regexp",
				"o": 0,
				"s": "project-(production|validation)-stage-topic"
			}
		}
	}
}
```


and here from the JVM pact file:
```
"matchingRules": {
	"metadata": {
		"kafka_topic": {
			"combine": "AND",
			"matchers": [{
				"match": "regex",
				"regex": "project-(production|validation)-stage-topic"
			}]
		}
	}
},
"metaData": {
	"contentType": "application/json",
	"kafka_topic": "project-production-stage-topic"
}
```

Note how the JS pact has the regex matching as part of the `metaData` object, whereas it's part of the `matchingRules` on the JVM side. 

Does this mean that we should've added the regex in a different place than `withMetadata` or is this really an issue with the serialization?

**Comment by mefellows** [comment]
Thank you for creating that repro. 

It seems that if there are matchers on the metadata it does this, but not if applied to the body.

@bethesque is that expected?

**Comment by bethesque** [comment]
Well, something is quite wrong because it shouldn't be serializing anything to a pact file with json_class. We haven't done that since version 2 came out, many years ago. Sorry, I haven't had a chance to sit down and do a deep dive on it.

**Comment by janeisenmenger** [comment]
Any update on this? :)

**Comment by mefellows** [comment]
No update that I'm aware, sorry.

Our [v3 branch](https://github.com/pact-foundation/pact-js/tree/feat/v3.0.0/) should resolve this issue, however it is still currently in beta and we're blocked on an upstream issue.

**Comment by mefellows** [comment]
10.x.x supports this. Marking as not supported for 9.x.x.
